#!/usr/bin/env python3
"""
Upload WideWorldImportersDW sample data to Supabase using MCP commands
This script creates the table and uploads the generated data.
"""

import pandas as pd
import json
import sys
import os
from generate_supabase_data import main as generate_data

PROJECT_ID = "kzujalwtfxipkvjeqtms"
TABLE_NAME = "wide-world-importers"

def prepare_data_for_supabase(df: pd.DataFrame) -> list:
    """Convert DataFrame to list of dictionaries for Supabase insertion"""
    records = df.to_dict('records')
    
    for record in records:
        for key, value in record.items():
            if pd.isna(value):
                record[key] = None
            elif isinstance(value, (pd.Timestamp, pd.DatetimeTZDtype)):
                record[key] = value.strftime('%Y-%m-%d') if pd.notna(value) else None
            elif hasattr(value, 'item'):
                record[key] = value.item()
    
    return records

def create_insert_statements(records: list, batch_size: int = 1000) -> list:
    """Create SQL INSERT statements for batched data insertion"""
    insert_statements = []
    
    for i in range(0, len(records), batch_size):
        batch = records[i:i + batch_size]
        
        if not batch:
            continue
            
        columns = list(batch[0].keys())
        column_names = ', '.join([f'"{col}"' for col in columns])
        
        values_clauses = []
        for record in batch:
            values = []
            for col in columns:
                value = record[col]
                if value is None:
                    values.append('NULL')
                elif isinstance(value, str):
                    escaped_value = value.replace("'", "''")
                    values.append(f"'{escaped_value}'")
                elif isinstance(value, bool):
                    values.append('TRUE' if value else 'FALSE')
                else:
                    values.append(str(value))
            values_clauses.append(f"({', '.join(values)})")
        
        values_part = ',\n    '.join(values_clauses)
        
        insert_sql = f"""
INSERT INTO "{TABLE_NAME}" ({column_names})
VALUES
    {values_part};
"""
        insert_statements.append(insert_sql)
    
    return insert_statements

def main():
    """Main function to generate data and prepare for Supabase upload"""
    print("WideWorldImportersDW to Supabase Data Upload")
    print("=" * 50)
    
    print("Step 1: Generating sample data...")
    sales_df = generate_data()
    
    if sales_df is None or len(sales_df) == 0:
        print("Error: No data generated!")
        return False
    
    print(f"Generated {len(sales_df)} sales records")
    
    print("\nStep 2: Preparing data for Supabase...")
    records = prepare_data_for_supabase(sales_df)
    print(f"Prepared {len(records)} records for insertion")
    
    print("\nStep 3: Creating INSERT statements...")
    insert_statements = create_insert_statements(records, batch_size=500)
    print(f"Created {len(insert_statements)} batch INSERT statements")
    
    print("\nStep 4: Saving SQL files...")
    
    with open('wide_world_importers_schema.sql', 'r') as f:
        schema_sql = f.read()
    
    for i, insert_sql in enumerate(insert_statements):
        filename = f'wide_world_importers_insert_batch_{i+1:03d}.sql'
        with open(filename, 'w') as f:
            f.write(insert_sql)
        print(f"  - {filename}")
    
    with open('wide_world_importers_complete.sql', 'w') as f:
        f.write("-- WideWorldImportersDW Sample Data for Supabase\n")
        f.write("-- Generated by upload-to-supabase.py\n\n")
        f.write("-- Step 1: Create table\n")
        f.write(schema_sql)
        f.write("\n\n-- Step 2: Insert data\n")
        for i, insert_sql in enumerate(insert_statements):
            f.write(f"-- Batch {i+1}\n")
            f.write(insert_sql)
            f.write("\n")
    
    print(f"  - wide_world_importers_complete.sql (master script)")
    
    total_revenue = sales_df['total_including_tax'].sum()
    total_profit = sales_df['profit'].sum()
    avg_margin = sales_df['margin_percentage'].mean()
    
    print(f"\nData Summary:")
    print("=" * 30)
    print(f"Total Records:                 {len(sales_df):,}")
    print(f"Total Revenue (12 months):     ${total_revenue:,.2f}")
    print(f"Total Profit (12 months):      ${total_profit:,.2f}")
    print(f"Average Margin Percentage:     {avg_margin:.2f}%")
    print(f"Date Range:                    {sales_df['invoice_date'].min()} to {sales_df['invoice_date'].max()}")
    print(f"Unique Customers:              {sales_df['customer_key'].nunique():,}")
    print(f"Unique Products:               {sales_df['stock_item_key'].nunique():,}")
    print(f"Unique Sales Territories:      {sales_df['sales_territory'].nunique():,}")
    
    monthly_stats = sales_df.groupby(['calendar_year', 'calendar_month_number']).agg({
        'total_including_tax': 'sum',
        'profit': 'sum',
        'margin_percentage': 'mean',
        'sale_key': 'count'
    }).round(2)
    monthly_stats.columns = ['Revenue', 'Profit', 'Avg_Margin_%', 'Transactions']
    
    print(f"\nMonthly Breakdown:")
    print(monthly_stats.to_string())
    
    print(f"\nNext Steps:")
    print("1. Use MCP commands to create the table in Supabase")
    print("2. Execute the INSERT statements to load the data")
    print("3. Verify the data was loaded correctly")
    
    return True, sales_df, insert_statements

if __name__ == "__main__":
    success, _, _ = main()
    sys.exit(0 if success else 1)
